### ISSUE TITLE
CORS:  No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by nolssmit** [bitnami/bitnami-docker-dreamfactory#23] opened 2021-07-05 08:10 UTC
I'm using TMS Software Web Core to create a web application.

See attached manual of my configurations, Dreamfactory, docker-compose.yml, router etc.

[DreamfactoryConfigs.pdf](https://github.com/bitnami/bitnami-docker-dreamfactory/files/6762716/DreamfactoryConfigs.pdf)

But if I run the application to access the database via the Rest interface, created by Dreamfactory, I get the following error response:

Access to XMLHttpRequest at 'https://slimzulu.hopto.org/api/v2/starsbib/_proc/json_publications_lookups(null,authors,keywords,media,publishers)?api_key=c5c143a1608482641961b9d33203826e637316d915987a640901de73ec807217' from origin 'https://slimzulu.hopto.org:8443' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

But if I execute the command: https://slimzulu.hopto.org/api/v2/starsbib/_proc/json_publications_lookups(null,authors,keywords,media,publishers)?api_key=c5c143a1608482641961b9d33203826e637316d915987a640901de73ec807217
then I do get a positive response.

I did configure Cors in Dreamfactory, see my attached manual.

Regards,

Nols Smit

**Comment by pablogalegoc** [comment] 2021-07-05 14:30
Hello @nolssmit,

It looks like the Dreamfactory Bitnami solution is working correctly and its configuration is fine. We are not able to reproduce this test scenario and I would recommend you to reach out to TMS Software Web Core's support so they can guide you on how to best setup their product to work with Dreamfactory.

**Comment by nolssmit** [comment] 2021-07-05 15:15
Hi Pablo,

If you open my website:  https://slimzulu.hopto.org:8443  and query the
certificate, you will see the hierarchy:

[image: image.png]

If try to open Dreamfactory my website:  https://slimzulu.hopto.org
<https://slimzulu.hopto.org:8443>

[image: image.png]

Remember the Rest API calls work thru Dreamfactory.

In Dreamfactory's configs, I created a service to access a PostgreSQL
database.  Under the service in the Configs section you have an option for
SSL Mode:

[image: image.png]

Whatever I type in (e.g. True) is rejected when I test it under Schema.

[image: image.png]

The question is:  How do I configure Dreamfactory to accept my SSL
certificate with the link: https://slimzulu.hopto.org
<https://slimzulu.hopto.org:8443> and to show the correct hierarchy of SSL
certificates such as when you access my web site:
https://slimzulu.hopto.org:8443

Regards,

Nols Smit

**Comment by pablogalegoc** [comment] 2021-07-07 07:28
Hi @nolssmit,

I didn't explain myself very well, sorry. What I meant is that your problem doesn't seem related to Bitnami Dreamfactory infrastructure (i.e. Docker and its configuration) but more on the configuration of Dreamfactory application itself. See if there's something of value for you in [their forum](https://community.dreamfactory.com/search?q=Access-Control-Allow-Origin%20order%3Alatest) or in any of the other [channels of support](https://www.dreamfactory.com/support/).

Regards!

**Comment by nolssmit** [comment] 2021-07-07 10:10
Hi Pablo,

First problem:  *Why*, if you access https://slimzulu.hopto.org:8443 and
query the SSL certificate you see:
[image: image.png]

*But*  when you access https://slimzulu.hopto.org
<https://slimzulu.hopto.org:8443> you have to confirm you trust the web
site:
[image: image.png]

Ten when you query the SSL certificate you see:

[image: image.png]

It's the same physical server.  Apache *did* interpret the SSL certificate
and the SSL chain file but Dreamfactory *did not*.

*My docker-compose.yml file:*
# https://hub.docker.com/r/bitnami/dreamfactory/
  dreamfactory:
    restart: unless-stopped
    container_name: dreamfactory
    image: bitnami/dreamfactory:latest
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - ***@***.***
      - SMTP_PASSWORD=xxxxxxxxxxxxxxxxxx
      - SMTP_PROTOCOL=tls
      - DREAMFACTORY_DATABASE_TYPE=mariadb
      - DREAMFACTORY_ENABLE_MARIADB_DATABASE=yes
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dreamfactory_data:/bitnami
    networks:
      - dreamfactory-tier
    depends_on:
      - mariadb
      - mongodb
      - redis

# https://github.com/bitnami/bitnami-docker-apache
  apache:
    restart: unless-stopped
    container_name: apache
    image: bitnami/apache:latest
    environment:
      - APACHE_HTTP_PORT_NUMBER=8080
      - APACHE_HTTPS_PORT_NUMBER=8443
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./apache_data:/app
      - ./apache-certs:/certs


Keep in mind all subsequent API Rest calls go through Dreamfactory.

Let's first solve this problem then we can look into the CORS problem.

Regards,

Nols Smit

**Comment by pablogalegoc** [comment] 2021-07-09 07:52
Hi @nolssmit,

I'll look into that and report back what I find! Just a quick note, you are attaching images in a reply via email but they are not being rendered in the Web. If you think they are relevant, please edit the comment when you have time.

**Comment by pablogalegoc** [comment] 2021-07-12 06:22
Hi @nolssmit,

It seems that Dreamfactory is using the default dummy SSL certificates at `/opt/bitnami/apache/conf/bitnami` for “example.com”. See [bitnami-docker-dreamfactory#customize-this-image ](https://github.com/bitnami/bitnami-docker-dreamfactory#customize-this-image)

**Comment by nolssmit** [comment] 2021-07-12 12:11
Hi Pablo,

I have endless problems trying to get one application running using a Rest
server created by using Dreamfactory.  I'm now busy exploring FastAPI.

Regards,

Nols Smit

**Comment by pablogalegoc** [comment] 2021-07-12 13:19
Sorry to hear that, hope you are more lucky with FastAPI!
I'll close this issue then.

Regards!

**Closed by pablogalegoc** 2021-07-12 13:19 UTC
